### ISSUE TITLE
buildworld errors out with "rtld_start.S: unknown pseudo-op: `.cfi_sections'"

### ISSUE THREAD

**Issue by yggdr** [sysadminmike/freebsd-onion-omega2-build#1]
Following your instructions, during `X_DTS_FILE=OMEGA2P.dts KERNCOFN=MT7628_FDT ../freebsd-wifi-build/build/bin/build ralink buildworld` in stage 4.3, I get
`/storage/scratch/onionfbsd/src/libexec/rtld-elf/mips/rtld_start.S: Assembler messages:
/storage/scratch/onionfbsd/src/libexec/rtld-elf/mips/rtld_start.S:35: Error: unknown pseudo-op: '.cfi_sections'
--- rtld_start.o ---
*** [rtld_start.o] Error code 1`
Any advise?

**Comment by sysadminmike** [comment]
not really - maybe dont include the ralink stuff - i only included it in my build as i had a ralink usb wifi adaptor as i was unable to get the built in one to work.
